version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db_App
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:      
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
        
    ports:
      - "5432:5432"